allowBuilds:
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - framer-motion@13.0.0
  - motion-dom@13.0.0
  - motion-utils@13.0.0
  - motion@13.0.0
